# This is a basic workflow to help you get started with Actions

name: statoshi.host

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    #paths:
    #  - 'GLOBAL'
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ubuntu-18-docker:
    runs-on: ubuntu-18.04
    steps:
      ## REF: https://githubmemory.com/repo/Gisleburt/cancel-workflow-action
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Make
        run: |
          git clone https://github.com/bitcoincore-dev/statoshi.host
          cd statoshi.host
          make init
          make header
          make run user=root

  ubuntu-20-docker:
    runs-on: ubuntu-20.04
    steps:
      ## REF: https://githubmemory.com/repo/Gisleburt/cancel-workflow-action
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Make
        run: |
          git clone https://github.com/bitcoincore-dev/statoshi.host
          cd statoshi.host
          make init
          make header
          make run user=root

