# This is a basic workflow to help you get started with Actions

name: stats.bitcoincore.dev

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    #paths:
    #  - 'GLOBAL'
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

################################################################################

  ubuntu-18-docker1:
    runs-on: ubuntu-18.04
    steps:
      ## REF: https://githubmemory.com/repo/Gisleburt/cancel-workflow-action
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: ubuntu-18-docker1
        run: |
          git clone https://github.com/bitcoincore-dev/stats.bitcoincore.dev
          cd stats.bitcoincore.dev
          make init header run user=root port=1234 verbose=true nocache=true

  macos-10-docker1:
    runs-on: macos-10.15
    steps:
      ## REF: https://githubmemory.com/repo/Gisleburt/cancel-workflow-action
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: macos-10-docker1
        run: |
          git clone https://github.com/bitcoincore-dev/stats.bitcoincore.dev
          cd stats.bitcoincore.dev
          make init header run user=root port=1234 verbose=true nocache=true

################################################################################

  ubuntu-18-docker2:
    runs-on: ubuntu-18.04
    steps:
      ## REF: https://githubmemory.com/repo/Gisleburt/cancel-workflow-action
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: macos-10-docker2
        run: |
          git clone https://github.com/bitcoincore-dev/stats.bitcoincore.dev
          cd stats.bitcoincore.dev
          make init header run user=root port=1234 verbose=true nocache=true

  macos-10-docker2:
    runs-on: macos-10.15
    steps:
      ## REF: https://githubmemory.com/repo/Gisleburt/cancel-workflow-action
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: macos-10-docker2
        run: |
          git clone https://github.com/bitcoincore-dev/stats.bitcoincore.dev
          cd stats.bitcoincore.dev
          make init header run user=root port=1234 verbose=true nocache=true

################################################################################
